export const LINKS_TYPE = {
  ADD_LINK: 'ADD_LINK',
  FILTER_BY_LIFE: 'FILTER_BY_LIFE',
  FILTER_BY: 'FILTER_BY',
  FILTER_BY_DEV: 'FILTER_BY_DEV',
  FILTER_BY_MOVIE: 'FILTER_BY_MOVIE',
  FILTER_BY_GAME: 'FILTER_BY_GAME'
}